#!/usr/bin/env node

const colors = require("colors");
const fs = require("fs");
const logger = require("js-logger");
const path = require("path");
const proc = require("child_process");

const { build } = require("esbuild");

const log = logger.get("Build");

logger.setDefaults({ useDefaults: true });

const options = {
    bundle: true,
    minify: true,
    sourcemap: true,
    target: "es6",
    platform: "node",
    logLevel: "error",
    legalComments: "none"
};

const tasks = [
    { input: path.resolve(__dirname, "src/EntrywayKeypad.ts"), output: path.resolve(__dirname, "lib/EntrywayKeypad.js") },
    { input: path.resolve(__dirname, "src/FoyerKeypad.ts"), output: path.resolve(__dirname, "lib/FoyerKeypad.js") },
    { input: path.resolve(__dirname, "src/KitchenRemote.ts"), output: path.resolve(__dirname, "lib/KitchenRemote.js") },
    { input: path.resolve(__dirname, "src/LivingRoomFan.ts"), output: path.resolve(__dirname, "lib/LivingRoomFan.js") },
    { input: path.resolve(__dirname, "src/LivingRoomRemote.ts"), output: path.resolve(__dirname, "lib/LivingRoomRemote.js") },
    { input: path.resolve(__dirname, "src/PrimaryBedroomRemote.ts"), output: path.resolve(__dirname, "lib/PrimaryBedroomRemote.js") }
];

const jobs = [];

fs.rmSync(path.resolve(__dirname, "lib"), { recursive: true, force: true });

for (let i = 0; i < tasks.length; i++) {
    const task = tasks[i];

    log.info(`esbuild ${colors.cyan(task.output)}`);

    jobs.push(build({ ...options, entryPoints: [task.input], outfile: task.output }));
}

Promise.all(jobs)
    .then(() => {
        log.info(`${colors.green("BUILD COMPLETE")}\n`);
    })
    .catch((error) => {
        log.error(error);
        log.error(`${colors.red("BUILD FAILED")}\n`);
    });
